name: "Pull Request Build"

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: setup-java-11
        name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: burrunan/gradle-cache-action@v1.6
        with:
          remote-build-cache-proxy-enabled: false
          arguments: test
  style:
    name: Stylecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: setup-java-11
        name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: burrunan/gradle-cache-action@v1.6
        with:
          remote-build-cache-proxy-enabled: false
          arguments: spotlessCheck
